name: CI_action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./speedfrontend  # frontend directory

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install frontend dependencies
      run: npm install

    - name: Run frontend lint
      run: npm run lint  # Linting command

    # - name: Run frontend tests
    #   run: npm test

    - name: Build frontend
      run: npm run build

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./speedbackend  # backend directory

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install backend dependencies
      run: npm install

    - name: Run backend lint
      run: npm run lint  # Linting command for backend

    - name: Run backend tests
      run: npm test  # Run tests for backend

    - name: Build backend
      run: npm run build
